language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer install --dev

script:
    - vendor/bin/phpunit -c phpunit.xml

before_deploy:
    - composer install --no-dev 
    - make phar

deploy:
    provider: releases
    api_key:
        secure: J6occOPhB/oaOS5hNsJTLHmaN1PeKS19+z5w0sqxNeJ8L0oLaObJmmyJBpn0RBYLaCxpABItC1LNkxj+aQzYPlTZZBx/3XPAlG265bCn/JeA2xnc9F88G13GNhvbSpFUkgllOHmGskmqQHWrjCzQ0ABV1tjkMFas6MNikXeA99A=
    file: karma.phar
    skip_cleanup: true
    on:
      tags: true
