language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install --dev

script:
    - vendor/bin/phpunit -c phpunit.xml

before_deploy:
    - composer install --no-dev
    - make phar

deploy:
    provider: releases
    api_key:
        secure: KUlnR2JrQzRiuoCQw5VARrR9anBeq7DrmURNwStyHHJl7ysV9rGK4G7O6axbU6twcuRjRo+J5thjlWWt+zan6x2mgkVZRCfOSz/zsc6a2cvoGq8klWEXd3jp/1rKstyS2rYDyYNffwZ3Hl6cUmPeM41DbOjIj1xXeBpbfCGMS8Y=
    file: karma.phar
    skip_cleanup: true
    on:
        tags: true
