language: php

php:
    - 7.4
before_script:
    - composer install

script:
    - vendor/bin/phpunit -c phpunit.xml

before_deploy:
    - composer install --no-dev
    - make phar

deploy:
    provider: releases
    api_key:
        secure: UHlwBFUGylOYVhiHnD98dQD3/unK+jyGjIL6MuxuF2Gk7nBbW9UPPZnjju3H5PcpuA/qtptgB4lwVx83ac0hiJKgEp3ipH3t44ftBOyfmrxxGrtdut+n8aW4jAlpnh0tRYjHl3tn3lr/bIqhNPZGlNH1sJtYaYz+s/xBwAdhop4=
    file: karma.phar
    skip_cleanup: true
    on:
        tags: true
