#!/usr/bin/env php
<?php

// Karma can be installed by phar or by composer (deprecated). Autoload.php is located differently in these cases
// Phar location needs to be tested first (__DIR__ is equals to phar://...)
$locations = [__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'];
foreach($locations as $file)
{
    if (file_exists($file))
    {
        require $file;
        break;
    }
}

$console = new Karma\Console(new Karma\Application());
$console->run();
